# hurry-dev is the local development version of hurry, built from the currently
# checked out source. This allows CI tests to run against the version being tested
# without conflicting with any production hurry installation.
#
# Uses production hurry to cache its own build. After this action runs, both
# `hurry` (production release) and `hurry-dev` (built from source) will be in PATH.

name: hurry-dev
description: Install and use hurry-dev (local development version)

inputs:
    hurry-api-token:
        description: "Hurry API token for caching"
        required: true

runs:
    using: composite
    steps:
        - name: Check if hurry-dev already in PATH
          id: check-path
          shell: bash
          run: |
              if command -v hurry-dev &> /dev/null; then
                echo "found=true" >> $GITHUB_OUTPUT
              else
                echo "found=false" >> $GITHUB_OUTPUT
              fi

        - name: Try to download artifact
          if: steps.check-path.outputs.found != 'true'
          id: download-artifact
          uses: actions/download-artifact@v4
          with:
              name: hurry-dev-binary
              path: /tmp/hurry
          continue-on-error: true

        - name: Check if download succeeded
          if: steps.check-path.outputs.found != 'true'
          id: check-download
          shell: bash
          run: |
              if [ -f /tmp/hurry/hurry-dev ]; then
                echo "found=true" >> $GITHUB_OUTPUT
              else
                echo "found=false" >> $GITHUB_OUTPUT
              fi

        - name: Install Rust toolchain
          if: steps.check-path.outputs.found != 'true' && steps.check-download.outputs.found != 'true'
          shell: bash
          run: |
              rustup toolchain install stable
              rustup show

        - name: Install production hurry
          if: steps.check-path.outputs.found != 'true' && steps.check-download.outputs.found != 'true'
          uses: ./.github/actions/hurry-install

        - name: Build hurry binary
          if: steps.check-path.outputs.found != 'true' && steps.check-download.outputs.found != 'true'
          shell: bash
          env:
              HURRY_API_TOKEN: ${{ inputs.hurry-api-token }}
          run: hurry cargo build --release --package hurry --verbose

        - name: Copy built binary to /tmp/hurry
          if: steps.check-path.outputs.found != 'true' && steps.check-download.outputs.found != 'true'
          shell: bash
          run: |
              mkdir -p /tmp/hurry
              cp target/release/hurry /tmp/hurry/hurry-dev

        - name: Upload artifact
          if: steps.check-path.outputs.found != 'true' && steps.check-download.outputs.found != 'true'
          uses: actions/upload-artifact@v4
          with:
              name: hurry-dev-binary
              path: /tmp/hurry/hurry-dev
          continue-on-error: true

        - name: Add hurry-dev to PATH
          if: steps.check-path.outputs.found != 'true'
          shell: bash
          run: |
              chmod +x /tmp/hurry/hurry-dev
              echo "/tmp/hurry" >> $GITHUB_PATH
